name: Terraform Static Checks

on:
  push:
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read


jobs:
  static-checks:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/test

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check -recursive ../../

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform